import { defineConfig } from 'vite'
import path from 'path'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'


function figmaAssetResolver() {
  return {
    name: 'figma-asset-resolver',
    resolveId(id) {
      if (id.startsWith('figma:asset/')) {
        const filename = id.replace('figma:asset/', '')
        return path.resolve(__dirname, 'src/assets', filename)
      }
    },
  }
}

export default defineConfig({
  plugins: [
    figmaAssetResolver(),
    // The React and Tailwind plugins are both required for Make, even if
    // Tailwind is not being actively used – do not remove them
    react(),
    tailwindcss(),
    VitePWA({
      // Generates + auto-updates the service worker on every deploy so
      // returning users pick up new builds without a manual uninstall.
      registerType: 'autoUpdate',
      injectRegister: 'auto',
      // Icons already live in /public (generated by
      // scripts/generate-pwa-icons.mjs from the app's own logo mark), so
      // just let them pass through to the build output as-is.
      includeAssets: ['favicon.svg', 'favicon-16x16.png', 'favicon-32x32.png', 'apple-touch-icon.png'],
      manifest: {
        name: 'DormiTrack',
        short_name: 'DormiTrack',
        description: 'DormiTrack is a premium app for university students that monitors boarding house information, manages payments, and connects students with parents and landlords for a secure living experience.',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        // Matches the app's own background/card color (see --background in
        // src/styles/theme.css) so the splash/launch transition is seamless.
        background_color: '#ffffff',
        // Matches the brand gradient used across headers/splash (GRAD_H in
        // src/app/shared.ts: #9772F6 -> #7549F6) — the darker stop reads
        // best as a single solid theme/status-bar color.
        theme_color: '#7549F6',
        orientation: 'portrait',
        icons: [
          { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: '/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        // Single-page app with no client-side router (see src/app/App.tsx —
        // navigation is in-memory state, not URL routes), so the only HTML
        // document that ever needs to be served offline is index.html.
        navigateFallback: '/index.html',
        globPatterns: ['**/*.{js,css,html,svg,png,ico,woff,woff2}'],
        // Never let the service worker cache Supabase auth/API/storage
        // traffic — always hit the network so sessions, data, and file
        // uploads stay live and never go stale from a cached response.
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/.*\.supabase\.co\/.*/i,
            handler: 'NetworkOnly',
          },
        ],
      },
      devOptions: {
        // Off during active development: a service worker running under `vite dev`
        // can keep serving a stale precached bundle across restarts, fighting
        // against normal edit-and-refresh — confusing when it's not expected.
        // `npm run build` + preview still gets the real SW for installability
        // testing; this only affects `vite dev`.
        enabled: false,
        type: 'module',
      },
    }),
  ],
  resolve: {
    alias: {
      // Alias @ to the src directory
      '@': path.resolve(__dirname, './src'),
    },
  },

  // File types to support raw imports. Never add .css, .tsx, or .ts files to this.
  assetsInclude: ['**/*.svg', '**/*.csv'],
})
