// Real DormiTrack logo artwork (location-pin + house mark), replacing the
// earlier placeholder inline-SVG shape. Two color variants generated by
// scripts/generate-pwa-icons.mjs from src/assets/logo-source/{1P,2W}.png:
// the purple mark for white/light backgrounds, the white mark for colored/
// gradient backgrounds — exactly what the existing `white` prop already
// meant, so every call site across the app (splash screen, login, admin
// sidebar, public landing page, etc.) needed zero changes.
export function DormiLogo({ size = 72, white = false }: { size?: number; white?: boolean }) {
  return (
    <img
      src={white ? "/logo-white.png" : "/logo-purple.png"}
      alt="DormiTrack"
      width={size}
      height={size}
      style={{ display: "block", width: size, height: size, objectFit: "contain" as const }}
    />
  );
}
